const root=document.documentElement,themeButton=document.querySelector('.theme-toggle'),progress=document.querySelector('.scroll-progress span'),filters=document.querySelectorAll('.filter'),cards=document.querySelectorAll('.project-card'),lensTabs=document.querySelectorAll('.lens-tab'),moreButton=document.querySelector('.more-projects');
const lensData={science:{title:'Find the signal',description:'I use forecasting, experimentation, and predictive modeling to turn noisy data into a decision someone can act on.',skills:['Forecasting','Anomaly detection','Causal inference','XGBoost','LightGBM','Scikit-learn'],node:'.node-ds'},ai:{title:'Put AI to work',description:'My AI work focuses on useful systems, from efficient LLM fine-tuning and retrieval to multimodal generation.',skills:['PyTorch','Generative AI','LoRA / QLoRA','RAG','LangChain','Multimodal AI'],node:'.node-ai'},engineering:{title:'Build the backbone',description:'I design the pipelines, transformations, and quality checks that let models and products hold up in production.',skills:['PySpark','Azure Databricks','SQL','AWS / Azure','Snowflake','MongoDB'],node:'.node-de'},visualization:{title:'Make the answer clear',description:'I turn complex analysis into dashboards, maps, and interactive stories that people can understand quickly.',skills:['Power BI / DAX','Tableau','D3.js','Plotly','GIS','Mapbox'],node:'.node-viz'}};
if(localStorage.getItem('rachit-theme')==='light'){root.dataset.theme='light';themeButton.setAttribute('aria-pressed','true');themeButton.setAttribute('aria-label','Switch to dark theme')}
themeButton.addEventListener('click',()=>{const wasLight=root.dataset.theme==='light';if(wasLight)delete root.dataset.theme;else root.dataset.theme='light';localStorage.setItem('rachit-theme',wasLight?'dark':'light');themeButton.setAttribute('aria-pressed',String(!wasLight));themeButton.setAttribute('aria-label',wasLight?'Switch to light theme':'Switch to dark theme')});
lensTabs.forEach(tab=>tab.addEventListener('click',()=>{const data=lensData[tab.dataset.lens];lensTabs.forEach(item=>{const active=item===tab;item.classList.toggle('is-active',active);item.setAttribute('aria-selected',String(active))});document.querySelectorAll('.node').forEach(node=>node.classList.remove('is-active'));document.querySelector(data.node).classList.add('is-active');document.querySelector('#lens-title').textContent=data.title;document.querySelector('#lens-description').textContent=data.description;document.querySelector('#lens-skills').innerHTML=data.skills.map(skill=>`<span>${skill}</span>`).join('')}));
document.querySelector('.node-ds').classList.add('is-active');
let allExpanded=false;
const applyFilter=selected=>{let visible=0;cards.forEach(card=>{const matches=selected==='all'||card.dataset.clusters.split(' ').includes(selected);const collapsed=selected==='all'&&card.classList.contains('project-secondary')&&!allExpanded;const show=matches&&!collapsed;card.classList.toggle('is-hidden',!show);if(show)visible++});moreButton.hidden=selected!=='all';moreButton.querySelector('span').textContent=allExpanded?'Show fewer projects':'Show 4 more projects';moreButton.setAttribute('aria-expanded',String(allExpanded));document.querySelector('.empty-state').hidden=visible>0};
filters.forEach(filter=>filter.addEventListener('click',()=>{const selected=filter.dataset.filter;filters.forEach(item=>item.classList.toggle('is-active',item===filter));applyFilter(selected)}));
moreButton.addEventListener('click',()=>{allExpanded=!allExpanded;applyFilter('all')});
applyFilter('all');
const revealObserver=new IntersectionObserver(entries=>entries.forEach(entry=>{if(entry.isIntersecting){entry.target.classList.add('is-visible');revealObserver.unobserve(entry.target)}}),{threshold:.1});document.querySelectorAll('.reveal').forEach(el=>revealObserver.observe(el));
const navLinks=document.querySelectorAll('nav a'),sectionObserver=new IntersectionObserver(entries=>entries.forEach(entry=>{if(entry.isIntersecting)navLinks.forEach(link=>link.classList.toggle('is-active',link.hash===`#${entry.target.id}`))}),{rootMargin:'-25% 0px -65% 0px'});document.querySelectorAll('section[id]').forEach(section=>sectionObserver.observe(section));
window.addEventListener('scroll',()=>{const scrollable=document.documentElement.scrollHeight-window.innerHeight;progress.style.width=`${scrollable>0?window.scrollY/scrollable*100:0}%`},{passive:true});document.querySelector('#year').textContent=new Date().getFullYear();
